# Federated PyTorch MNIST Tutorial

In [1]:
#Install dependencies if not already installed
!pip install torch torchvision ..

Processing /home/itrushkin/repos/openfl-fork


  Created wheel for openfl: filename=openfl-1.0.1-py3-none-any.whl size=4252631 sha256=fe29dccb713b5ee8a126f764e9619c0ec6d10a1db1d0bce05e2182c527298391
  Stored in directory: /home/itrushkin/.cache/pip/wheels/ed/ad/82/f26baafab4be32d052fb76a6f56c9a76ce6903cc3eed7bb394
Successfully built openfl
  Attempting uninstall: openfl
    Found existing installation: openfl 1.0.1
    Uninstalling openfl-1.0.1:
      Successfully uninstalled openfl-1.0.1
You should consider upgrading via the '/home/itrushkin/.virtualenvs/openfl_research/bin/python -m pip install --upgrade pip' command.


In [2]:
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

import torchvision
import torchvision.transforms as transforms
import openfl.native as fx
from openfl.federated import FederatedModel,FederatedDataSet


After importing the required packages, the next step is setting up our openfl workspace. To do this, simply run the `fx.init()` command as follows:

In [3]:
#Setup default workspace, logging, etc.
fx.init('torch_cnn_mnist')

Creating Workspace Directories
Creating Workspace Templates

New workspace directory structure:
workspace
├── plan
│   ├── defaults
│   │   ├── data_loader.yaml
│   │   ├── network.yaml
│   │   ├── tasks_keras.yaml
│   │   ├── collaborator.yaml
│   │   ├── assigner.yaml
│   │   ├── task_runner.yaml
│   │   ├── defaults
│   │   ├── tasks_tensorflow.yaml
│   │   ├── aggregator.yaml
│   │   ├── tasks_torch.yaml
│   │   └── tasks_fast_estimator.yaml
│   ├── plan.yaml
│   ├── data.yaml
│   └── cols.yaml
├── logs
├── agg_to_col_two_signed_cert.zip
├── data
│   └── MNIST
│       ├── raw
│       └── processed
├── cert
│   ├── ca
│   │   ├── signing-ca.crt
│   │   ├── root-ca.crt
│   │   ├── signing-ca
│   │   ├── signing-ca.csr
│   │   └── root-ca
│   ├── server
│   │   ├── agg_nnlicv611.inn.intel.com.csr
│   │   ├── agg_nnlicv611.inn.intel.com.key
│   │   └── agg_nnlicv611.inn.intel.com.crt
│   ├── client
│   │   ├── col_two.crt
│   │   ├── col_one.crt
│   │   ├── col_one.key
│   │   └── col_

Now we are ready to define our dataset and model to perform federated learning on. The dataset should be composed of a numpy arrayWe start with a simple fully connected model that is trained on the MNIST dataset. 

In [4]:
def one_hot(labels, classes):
    return np.eye(classes)[labels]

transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))])

trainset = torchvision.datasets.MNIST(root='./data', train=True,
                                        download=True, transform=transform)

train_images,train_labels = trainset.train_data, np.array(trainset.train_labels)
train_images = torch.from_numpy(np.expand_dims(train_images, axis=1)).float()
train_labels = one_hot(train_labels,10)

validset = torchvision.datasets.MNIST(root='./data', train=False,
                                       download=True, transform=transform)

valid_images,valid_labels = validset.test_data, np.array(validset.test_labels)
valid_images = torch.from_numpy(np.expand_dims(valid_images, axis=1)).float()
valid_labels = one_hot(valid_labels,10)

/home/itrushkin/.virtualenvs/openfl_research/lib/python3.8/site-packages/torchvision/datasets/mnist.py:64: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
/home/itrushkin/.virtualenvs/openfl_research/lib/python3.8/site-packages/torchvision/datasets/mnist.py:54: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")
/home/itrushkin/.virtualenvs/openfl_research/lib/python3.8/site-packages/torchvision/datasets/mnist.py:69: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/home/itrushkin/.virtualenvs/openfl_research/lib/python3.8/site-packages/torchvision/datasets/mnist.py:59: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


In [5]:
feature_shape = train_images.shape[1]
classes       = 10

fl_data = FederatedDataSet(train_images,train_labels,valid_images,valid_labels,batch_size=32,num_classes=classes)

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 16, 3)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(16, 32, 3)
        self.fc1 = nn.Linear(32 * 5 * 5, 32)
        self.fc2 = nn.Linear(32, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = x.view(x.size(0),-1)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
optimizer = lambda x: optim.Adam(x, lr=1e-4)

def cross_entropy(output, target):
    """Binary cross-entropy metric
    """
    return F.cross_entropy(input=output,target=torch.argmax(target, dim=1))

In [6]:

#Create a federated model using the pytorch class, lambda optimizer function, and loss function
fl_model = FederatedModel(build_model=Net,optimizer=optimizer,loss_fn=cross_entropy,data_loader=fl_data)

The `FederatedModel` object is a wrapper around your Keras, Tensorflow or PyTorch model that makes it compatible with openfl. It provides built in federated training and validation functions that we will see used below. Using it's `setup` function, collaborator models and datasets can be automatically defined for the experiment. 

In [7]:
collaborator_models = fl_model.setup(num_collaborators=2)
collaborators = {'one':collaborator_models[0],'two':collaborator_models[1]}#, 'three':collaborator_models[2]}

In [8]:
#Original MNIST dataset
print(f'Original training data size: {len(train_images)}')
print(f'Original validation data size: {len(valid_images)}\n')

#Collaborator one's data
print(f'Collaborator one\'s training data size: {len(collaborator_models[0].data_loader.X_train)}')
print(f'Collaborator one\'s validation data size: {len(collaborator_models[0].data_loader.X_valid)}\n')

#Collaborator two's data
print(f'Collaborator two\'s training data size: {len(collaborator_models[1].data_loader.X_train)}')
print(f'Collaborator two\'s validation data size: {len(collaborator_models[1].data_loader.X_valid)}\n')

#Collaborator three's data
#print(f'Collaborator three\'s training data size: {len(collaborator_models[2].data_loader.X_train)}')
#print(f'Collaborator three\'s validation data size: {len(collaborator_models[2].data_loader.X_valid)}')

Original training data size: 60000
Original validation data size: 10000

Collaborator one's training data size: 30000
Collaborator one's validation data size: 5000

Collaborator two's training data size: 30000
Collaborator two's validation data size: 5000



We can see the current plan values by running the `fx.get_plan()` function

In [9]:
 #Get the current values of the plan. Each of these can be overridden
import json
print(json.dumps(fx.get_plan(), indent=4, sort_keys=True))

{
    "aggregator.settings.best_state_path": "save/torch_cnn_mnist_best.pbuf",
    "aggregator.settings.db_store_rounds": 1,
    "aggregator.settings.init_state_path": "save/torch_cnn_mnist_init.pbuf",
    "aggregator.settings.last_state_path": "save/torch_cnn_mnist_last.pbuf",
    "aggregator.settings.rounds_to_train": 10,
    "aggregator.template": "openfl.component.Aggregator",
    "assigner.settings.task_groups": [
        {
            "name": "train_and_validate",
            "percentage": 1.0,
            "tasks": [
                "aggregated_model_validation",
                "train",
                "locally_tuned_model_validation"
            ]
        }
    ],
    "assigner.template": "openfl.component.RandomGroupedAssigner",
    "collaborator.settings.db_store_rounds": 1,
    "collaborator.settings.delta_updates": false,
    "collaborator.settings.opt_treatment": "RESET",
    "collaborator.template": "openfl.component.Collaborator",
    "data_loader.settings.batch_size": 2

Now we are ready to run our experiment. If we want to pass in custom plan settings, we can easily do that with the `override_config` parameter

In [10]:
def agg_func(tensors, data_sizes):
    return np.median(tensors, axis=0)

In [11]:
#Run experiment, return trained FederatedModel
final_fl_model = fx.run_experiment(collaborators,
                                   {
                                       'aggregator.settings.rounds_to_train':5,
                                       'tasks.train.aggregation_type': agg_func
                                   })

/home/itrushkin/.virtualenvs/openfl_research/lib/python3.8/site-packages/openfl/federated/task/runner_pt.py:277: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:143.)
  new_state[k] = pt.from_numpy(tensor_dict.pop(k)).to(device)
/home/itrushkin/.virtualenvs/openfl_research/lib/python3.8/site-packages/openfl/federated/task/runner_pt.py:102: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  data, target = pt.tensor(data).to(self.device), pt.tensor(

/home/itrushkin/.virtualenvs/openfl_research/lib/python3.8/site-packages/openfl/federated/task/runner_pt.py:453: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  data, target = pt.tensor(data).to(self.device), pt.tensor(


[0.5092638  0.48201922]


[[[[[ 0.05508939  0.3038397  -0.15677142]
    [ 0.31266254  0.3103413   0.01070586]
    [-0.23311372 -0.02905526  0.32964092]]]


  [[[-0.20531528 -0.04859953 -0.23389588]
    [-0.17773783 -0.32326683 -0.19086799]
    [-0.2723774   0.19368768 -0.07539539]]]


  [[[-0.07317927 -0.23705226 -0.05293163]
    [-0.25901493 -0.05397716 -0.2818169 ]
    [ 0.05445158 -0.0809221  -0.03989086]]]


  [[[-0.08725324 -0.1642036   0.28098962]
    [-0.05006864 -0.24969605  0.25193733]
    [ 0.10399592  0.18565118  0.19510177]]]


  [[[ 0.19113791  0.2871135  -0.10628295]
    [ 0.22252427  0.18861082 -0.14566435]
    [ 0.33799762 -0.1803908   0.12877984]]]


  [[[ 0.23775768 -0.16379051  0.24598661]
    [-0.16855513  0.00096856  0.15354462]
    [-0.29281482  0.06796147  0.27010512]]]


  [[[-0.31956393 -0.2470507   0.12252438]
    [ 0.27900383 -0.12651865 -0.14420539]
    [ 0.3116548   0.08403204  0.20537864]]]


  [[[ 0.23872446  0.11108732 -0.3225457 ]
    [ 0.22773597 -0.14045076 -0.27741787]
    [-

[[7.8871682e-07 5.7357943e-07 1.8322781e-06 1.4789351e-06 1.5489397e-07
  6.5478622e-07 1.4786682e-06 9.7491829e-07 7.6849329e-07 5.1625977e-07
  9.7036548e-07 1.4632564e-06 5.4890859e-07 1.2929435e-06 1.1026518e-06
  6.1041288e-07 6.7470978e-07 5.2626098e-07 1.0822280e-06 1.0056079e-06
  8.3605249e-07 6.5220667e-07 1.0270927e-06 7.3098681e-07 8.0492777e-07
  6.2886176e-07 7.8775673e-07 6.1632727e-07 6.7934553e-07 8.3091044e-07
  8.2824022e-07 4.8157915e-07]
 [5.6246307e-07 6.5081650e-07 1.5200515e-06 9.0950681e-07 2.5539430e-07
  6.6673857e-07 1.6168153e-06 9.2673969e-07 9.4645287e-07 6.0294889e-07
  9.4141274e-07 8.0933614e-07 3.8079060e-07 1.2711051e-06 1.1653485e-06
  5.5507098e-07 5.4213137e-07 5.7649044e-07 9.4675704e-07 9.9473402e-07
  8.1394217e-07 4.9290855e-07 1.1154278e-06 7.5392734e-07 6.8082903e-07
  6.3998772e-07 9.4552809e-07 5.8934779e-07 5.8977650e-07 8.5586004e-07
  8.6790823e-07 5.0211412e-07]]
[[938.]
 [938.]]
[[[ 3.1767209e-04  4.5695502e-05  2.7456004e-03 ...  1.1

[0.15255146 0.1459973 ]


[[[[[ 0.05980016  0.3085888  -0.15521798]
    [ 0.31632912  0.31440732  0.01374757]
    [-0.23077986 -0.02845279  0.3299004 ]]]


  [[[-0.2019742  -0.0459592  -0.23012115]
    [-0.17715253 -0.3101219  -0.18774924]
    [-0.26482978  0.20347059 -0.07275121]]]


  [[[-0.07249072 -0.23498039 -0.04505156]
    [-0.25557888 -0.0467008  -0.28332233]
    [ 0.06520481 -0.0774415  -0.04188971]]]


  [[[-0.09360963 -0.16387188  0.2829431 ]
    [-0.05325982 -0.24949862  0.25486973]
    [ 0.09895669  0.18206212  0.19452573]]]


  [[[ 0.19045676  0.28839362 -0.10210332]
    [ 0.2210036   0.18879649 -0.14490642]
    [ 0.3359625  -0.18210076  0.12470798]]]


  [[[ 0.23741314 -0.15511668  0.25016743]
    [-0.16963746  0.00600278  0.15648656]
    [-0.2977823   0.06506797  0.27081925]]]


  [[[-0.32362396 -0.2530103   0.11492895]
    [ 0.27807906 -0.12721989 -0.14639598]
    [ 0.31166285  0.08597207  0.20602964]]]


  [[[ 0.23934937  0.10588768 -0.32905644]
    [ 0.23117866 -0.13744895 -0.27708846]
    [-

[[2.58163737e-07 5.36137122e-07 6.18511649e-07 9.94667971e-07
  3.65825201e-07 5.12415340e-07 6.37272365e-07 4.75124324e-07
  6.45238856e-07 1.12774039e-07 3.52902305e-07 5.56164991e-07
  2.16745644e-08 6.76286959e-07 2.10348617e-07 2.37176636e-07]
 [2.96982449e-07 5.78106210e-07 6.57262376e-07 9.23427763e-07
  4.37481617e-07 5.44343493e-07 6.02415128e-07 4.03485984e-07
  5.83906626e-07 1.16750115e-07 4.04231770e-07 5.15923091e-07
  2.18580105e-08 6.75886383e-07 2.15862258e-07 2.07264776e-07]]
[[1876.]
 [1876.]]
[[[[[-6.14561141e-03  3.08431033e-03  1.22080427e-02]
    [-1.20500783e-02 -6.85191108e-03 -2.21901597e-03]
    [ 5.81445545e-03  3.28861200e-03  5.19145513e-03]]

   [[ 4.18193347e-04  3.03345500e-04  1.95229775e-04]
    [ 7.78536487e-05 -3.37250412e-06  3.50783346e-04]
    [-2.85504764e-04  8.48895361e-05 -7.53896003e-08]]

   [[-1.80162897e-04 -6.43178704e-04 -3.13187222e-04]
    [ 1.29925305e-04  1.74200730e-04  4.29685224e-06]
    [ 1.18470423e-04 -1.15606825e-04 -1.640678

[[1.44883306e-05 7.04704632e-07 3.67237521e-06 1.09133234e-05
  1.32299701e-05 1.26216382e-05 3.70181397e-06 8.23828850e-06
  5.70380028e-11 6.75458932e-06 1.51278499e-07 1.13403644e-07
  1.99439810e-07 1.35755145e-05 1.72097898e-05 6.68082475e-06
  8.48927266e-06 2.82295923e-06 4.47123421e-06 9.83605150e-06
  1.81858559e-06 1.91165891e-05 0.00000000e+00 9.21670107e-06
  3.53617656e-06 7.07929166e-06 6.43559679e-06 1.59866395e-05
  1.56933220e-05 7.84730037e-06 1.50769010e-05 5.19230525e-06
  4.96676148e-06 3.77937141e-07 4.97547671e-06 3.35500818e-06
  8.61766864e-07 2.08413962e-06 2.63938034e-07 3.67565463e-06
  1.59295414e-05 2.02026507e-09 1.23318332e-05 2.42332931e-06
  3.82592134e-06 1.44121004e-05 1.31424222e-05 1.77740489e-08
  8.23575010e-06 1.58149269e-05 8.50408867e-07 1.09463798e-07
  1.03936763e-05 2.82121664e-06 2.51119013e-06 3.30615740e-06
  8.72306657e-07 0.00000000e+00 1.43746001e-05 6.98273061e-06
  1.81646965e-06 8.33975537e-06 6.02741252e-08 1.16241299e-05
  1.2096

[0.09779201 0.10037234]


[[[[[ 0.05601729  0.30580106 -0.1590994 ]
    [ 0.317455    0.31636253  0.01531238]
    [-0.23173913 -0.02535312  0.329258  ]]]


  [[[-0.19620346 -0.0403901  -0.21826108]
    [-0.1739093  -0.3066005  -0.19062191]
    [-0.25539637  0.21291962 -0.06782837]]]


  [[[-0.07462173 -0.22989708 -0.03786803]
    [-0.24443513 -0.04019843 -0.28391826]
    [ 0.07717145 -0.06911181 -0.04005244]]]


  [[[-0.09839893 -0.16589132  0.28324696]
    [-0.05741432 -0.24913365  0.25696257]
    [ 0.09663463  0.18136425  0.19633742]]]


  [[[ 0.18939477  0.28696182 -0.10282232]
    [ 0.22090644  0.18944508 -0.14597178]
    [ 0.3374324  -0.17974383  0.12285403]]]


  [[[ 0.23226902 -0.15694688  0.24851908]
    [-0.17514634  0.00367534  0.15829913]
    [-0.30382618  0.0607886   0.26981884]]]


  [[[-0.33092904 -0.25964546  0.10907007]
    [ 0.2714421  -0.1305556  -0.15175502]
    [ 0.3081497   0.08623531  0.20401345]]]


  [[[ 0.23898189  0.10668766 -0.33270264]
    [ 0.2342144  -0.13384601 -0.27914637]
    [-

[[2814.]
 [2814.]]
[[[ 2.73567116e-06  4.98763518e-04  6.49839407e-03 ...  1.26561197e-02
    2.81945104e-04  3.21827865e-05]
  [-2.96970975e-04 -4.53756144e-03  4.16652532e-03 ...  4.39015403e-03
   -7.54260179e-03 -1.16057845e-03]
  [-2.27703387e-03 -4.96908557e-03 -4.94189840e-03 ...  4.98964917e-03
    1.28490068e-02  6.46439707e-03]
  ...
  [ 3.83055350e-03  1.40830660e-02  1.94889456e-02 ...  3.28872795e-03
   -5.85661177e-03  9.45956260e-03]
  [ 1.10613857e-03  6.28478965e-03  1.37265446e-02 ...  1.78656336e-02
    3.39512760e-03  4.85416828e-03]
  [ 1.35670358e-03  5.00547560e-03  5.41851809e-03 ...  3.59237869e-03
    1.69461183e-02  1.40521321e-02]]

 [[ 4.10060693e-07 -1.05443709e-04 -1.61231263e-03 ... -2.31190072e-03
   -2.99324119e-03 -1.33548293e-03]
  [-1.16303825e-04 -2.97062215e-04  1.34765272e-04 ... -2.33000799e-04
   -1.82675736e-04  7.42624281e-04]
  [-6.07397269e-05  3.23241926e-03  7.28516979e-03 ... -1.16677853e-04
    3.56086763e-03 -1.05335959e-03]
  ...
  [ 

[0.07760414 0.08187568]


[[[[[ 0.05726683  0.30737886 -0.16049182]
    [ 0.31813058  0.31812415  0.01620419]
    [-0.23331986 -0.02425498  0.3292798 ]]]


  [[[-0.19288132 -0.04010929 -0.21847424]
    [-0.1751339  -0.29523405 -0.18517181]
    [-0.2466312   0.22421105 -0.06034244]]]


  [[[-0.07297665 -0.2225209  -0.03337949]
    [-0.23977122 -0.04249298 -0.2789126 ]
    [ 0.0856631  -0.0657837  -0.03757599]]]


  [[[-0.10374209 -0.17027071  0.28067172]
    [-0.05972885 -0.25078672  0.25568283]
    [ 0.09462528  0.17872992  0.19465138]]]


  [[[ 0.18737659  0.28575918 -0.10298403]
    [ 0.22093907  0.19080704 -0.1453662 ]
    [ 0.33803302 -0.17788202  0.12346053]]]


  [[[ 0.22807121 -0.15694828  0.24828935]
    [-0.1798534   0.00355239  0.15767603]
    [-0.30851272  0.05885392  0.2693111 ]]]


  [[[-0.33249632 -0.26106712  0.10439437]
    [ 0.26986802 -0.13047703 -0.15426317]
    [ 0.30852944  0.0886574   0.2030118 ]]]


  [[[ 0.23725276  0.10248722 -0.33771858]
    [ 0.23580505 -0.13147646 -0.27917612]
    [-

[[2.9409176e-07 6.9995451e-07 1.1033795e-06 4.0460003e-07 7.2867414e-07
  1.3796023e-06 7.0734154e-07 4.2213878e-07 4.1611170e-07 7.1633565e-07
  6.1984719e-07 7.8131978e-07 2.6231660e-07 1.0347470e-06 4.8724047e-07
  2.8913297e-07 6.8606431e-07 5.0376337e-07 5.7938638e-07 4.7319375e-07
  3.7427878e-07 5.5961635e-07 7.7826792e-07 6.2251422e-07 8.9617356e-07
  3.8134888e-07 3.9056840e-07 4.7539888e-07 3.5486113e-07 5.6255641e-07
  5.6855623e-07 1.1771875e-06]
 [2.8496879e-07 7.0411272e-07 1.1153609e-06 3.8501349e-07 5.9571732e-07
  1.3896735e-06 7.5006596e-07 4.8386130e-07 4.8115135e-07 7.5078248e-07
  6.8401044e-07 7.2269603e-07 2.6713994e-07 9.7156590e-07 5.3198465e-07
  2.6702546e-07 6.8917171e-07 5.3775301e-07 6.7463816e-07 4.5855353e-07
  3.5587220e-07 5.6794369e-07 8.1789909e-07 6.0469455e-07 9.2999983e-07
  3.7784551e-07 4.0394914e-07 4.6045412e-07 3.5844937e-07 6.2698234e-07
  5.9368148e-07 1.2214863e-06]]
[[3752.]
 [3752.]]
[[[-7.71214127e-06 -1.47722822e-04 -2.60142406e-04 ...

[0.06514921 0.06826576]


[[[[[ 0.05730506  0.30770686 -0.15992267]
    [ 0.31842792  0.31939965  0.01722945]
    [-0.23548852 -0.02404473  0.32777685]]]


  [[[-0.19095527 -0.03594233 -0.22296064]
    [-0.1778941  -0.29089728 -0.18586223]
    [-0.24320899  0.23040733 -0.05795427]]]


  [[[-0.0712956  -0.22346471 -0.02998039]
    [-0.23064479 -0.03537453 -0.28135335]
    [ 0.09304883 -0.06229437 -0.03881381]]]


  [[[-0.1080092  -0.17251417  0.2804981 ]
    [-0.0627408  -0.25108325  0.25717133]
    [ 0.09141191  0.17726019  0.19422948]]]


  [[[ 0.18451956  0.28467074 -0.10483456]
    [ 0.21969168  0.19093259 -0.14664821]
    [ 0.3369443  -0.1785183   0.12237554]]]


  [[[ 0.22599941 -0.1542556   0.24822934]
    [-0.18177211  0.00442567  0.15826514]
    [-0.31071293  0.05866947  0.2697056 ]]]


  [[[-0.33370787 -0.26255503  0.10248559]
    [ 0.26906744 -0.1296628  -0.15590683]
    [ 0.30863068  0.09078141  0.20230868]]]


  [[[ 0.2360678   0.10072105 -0.3400973 ]
    [ 0.23776196 -0.12744698 -0.27771163]
    [-

[[[[[8.07516836e-03 6.04276685e-03 6.27330225e-03]
    [9.37913358e-03 8.94849841e-03 8.27789027e-03]
    [5.63887786e-03 6.56201411e-03 8.57316982e-03]]

   [[7.10034146e-06 5.42422231e-06 4.78069660e-06]
    [8.72173700e-07 9.65846766e-07 1.79436097e-06]
    [2.12583288e-07 1.62704836e-07 3.44437893e-07]]

   [[2.00423733e-06 5.05241997e-06 6.80401308e-06]
    [1.26600881e-07 5.11915516e-07 1.97179520e-06]
    [6.07711456e-07 3.47164672e-07 1.44823673e-07]]

   ...

   [[7.43497920e-04 7.29445135e-04 6.43041451e-04]
    [5.83377085e-04 6.67702116e-04 8.06928554e-04]
    [3.94391565e-04 5.09928446e-04 4.31917753e-04]]

   [[1.09715702e-03 9.46533866e-04 1.18762837e-03]
    [2.06626719e-03 1.71606720e-03 1.55341509e-03]
    [1.58364780e-03 1.57793437e-03 1.68593053e-03]]

   [[6.01950778e-05 6.79352306e-05 6.60308942e-05]
    [3.63858635e-05 7.70828483e-05 3.93165392e-05]
    [4.53056164e-05 5.00003953e-05 5.18337401e-05]]]


  [[[9.14504193e-03 1.52263036e-02 1.59412101e-02]
    [1.32

[[2.4108127e-07 6.7255365e-07 9.5749465e-07 3.0594308e-07 7.3666558e-07
  1.2614234e-06 6.2880400e-07 3.7190958e-07 3.8009637e-07 8.6811463e-07
  5.6298268e-07 6.5572448e-07 2.5599516e-07 9.6734721e-07 3.9030056e-07
  2.5795717e-07 7.3258411e-07 5.0221581e-07 5.6900939e-07 3.6527587e-07
  3.1102454e-07 5.2874441e-07 7.5379756e-07 5.5459253e-07 8.1145544e-07
  3.4888546e-07 3.1196959e-07 4.0902029e-07 3.1433959e-07 5.1102541e-07
  5.0106024e-07 1.1412772e-06]
 [2.5010837e-07 6.5185986e-07 9.8742885e-07 3.1820562e-07 6.5953094e-07
  1.2750792e-06 6.2589601e-07 3.9460912e-07 3.9483527e-07 8.3401113e-07
  6.2538294e-07 6.1083358e-07 2.5070617e-07 9.1949238e-07 4.4038748e-07
  2.3732375e-07 7.3712687e-07 4.7854974e-07 6.8801239e-07 3.5759169e-07
  3.0584457e-07 5.2721794e-07 7.9226800e-07 5.2125046e-07 8.7592844e-07
  3.2414528e-07 3.1665249e-07 4.1303392e-07 3.1319982e-07 5.6562504e-07
  5.0854771e-07 1.1411571e-06]]
[[4690.]
 [4690.]]
[[[ 7.3996029e-07  5.1835930e-04  1.0189334e-03 ... -8

[[4690.]
 [4690.]]
[[-4.0848632e-03 -4.2811516e-04  4.7489672e-04  5.2675820e-04
   1.0106217e-03  6.9172739e-04  4.2297761e-03 -1.7057484e-03
  -5.1159627e-04 -2.0346213e-04]
 [ 8.1323400e-05 -7.1820494e-04  1.8740875e-03 -3.9448743e-03
   1.8609125e-03  5.1514269e-04  7.7602075e-04 -1.7314232e-03
   2.3590822e-03 -1.0720687e-03]]
[[6.7811539e-05 7.0177084e-05 1.3945648e-04 1.5393175e-04 1.0915299e-04
  1.3651601e-04 8.5066102e-05 1.4115413e-04 2.0782962e-04 1.7818090e-04]
 [8.8793713e-05 7.3492149e-05 1.3444672e-04 1.4215309e-04 1.2956756e-04
  1.3137267e-04 9.8142322e-05 1.3512500e-04 1.9423064e-04 1.9385859e-04]]
[[10.]
 [10.]]


In [12]:
#Save final model
final_fl_model.save_native('final_pytorch_model')

In [13]:
import pickle
print(pickle.dumps(1))

b'\x80\x04K\x01.'
